version: '3.8'

services:
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    depends_on:
      - gitlab
    networks:
      - internal
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/etc/gitlab-runner
    environment:
      # Runner auto-registration
      CI_SERVER_URL: "https://akira.ngrok.dev/"
      REGISTRATION_TOKEN: "glrt-2Q2Nfb2_M9PlT1bcFAyWDm86MQp0OjEKdTozCw.01.120e8nbrv"
      RUNNER_NAME: "local-docker-runner"
      RUNNER_EXECUTOR: "docker"
      DOCKER_IMAGE: "docker:stable"
    deploy:
      replicas: 1

networks:
  internal:
    driver: overlay
  web:
    external: true

volumes:
  gitlab-runner-config:
