concurrent = 8
check_interval = 0

[[runners]]
  name = "local-docker-runner"
  url = "https://akira.ngrok.dev/"
  token = "glrt-2Q2Nfb2_M9PlT1bcFAyWDm86MQp0OjEKdTozCw.01.120e8nbrv"
  executor = "docker"

  [runners.docker]
    tls_verify = false
    image = "docker:stable"
    privileged = true
    disable_cache = false
    volumes = ["/cache", "/var/run/docker.sock:/var/run/docker.sock"] 
